name: ci-pull-request

on: 
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}    
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    # This checkouts the repo, otherwise folder will be empty
    # Use the version 2 so you can push back the changes
    - uses: actions/checkout@v2

    # Running my script. Make sure it's executable (chmod +x ./.github/script.sh)
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Check properties of Pull Request
      run: python .github/check_pull_request.py  "$REPO" "$PR_NUMBER" "$TOKEN"

    - name: Linting
      run: flake8 .

    - name: Run the program
      run: python main.py

    # Commit the changes
    #- name: If everything looks good, commit changes
    #  run: |
    #    git config --global user.name 'Auto-Pull-Request'
    #    git config --global user.email 'sebastiandres@users.noreply.github.com'
    #    git commit -am "Merging pull request with github actions"
    #    git push
