# https://docs.github.com/es/actions/reference/environment-variables
name: CI
on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TEST: 7
      PR_NUMBER: ${{ github.event.pull_request.number }}    
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Repo
      run: echo "$GITHUB_REPOSITORY"
    - name: Test env variables
      run: echo "$TEST"
    - name: Pull request number
      run: echo "$PR_NUMBER"
    - name: Token
      run: echo "$TOKEN"
