# https://docs.github.com/es/actions/reference/environment-variables
name: manual show variables
on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TEST: 42
      PR_NUMBER: ${{ github.event.pull_request.number }}    
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Repo
      run: echo "$GITHUB_REPOSITORY"
    - name: Test env variables
      run: echo "$TEST"
    - name: Pull request number
      run: echo "$PR_NUMBER"
    - name: Token
      run: echo "$TOKEN"
    - name: Run python
      run: python .github/print_all_args.py "$GITHUB_REPOSITORY" "TEST" "$PR_NUMBER" "$TOKEN"