# https://docs.github.com/es/actions/reference/environment-variables
name: CI
on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}    

    steps:
    - uses: actions/checkout@v2

    - name: Repo
      run: echo "$GITHUB_REPOSITORY"
    - name: Pull request number
      run: echo ${{ PR_NUMBER }}
    - name: Token
      run: echo ${{ secrets.GITHUB_TOKEN }}
