# https://docs.github.com/es/actions/reference/environment-variables
name: manually print arguments
on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TEST: 42
      PR_NUMBER: ${{ github.event.pull_request.number }}    
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    # This checkouts the repo, otherwise folder will be empty
    - uses: actions/checkout@v2
    - name: Repo
      run: echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
    - name: Test env variables
      run: echo "TEST: $TEST"
    - name: Pull request number
      run: echo "PR_NUMBER: $PR_NUMBER"
    - name: Token
      run: echo "TOKEN: $TOKEN"
    - name: Run python
      run: python .github/print_all_args.py "$GITHUB_REPOSITORY" "$TEST" "$PR_NUMBER" "$TOKEN"